name: Monitor de Preços ML

on:
  schedule:
    - cron: '0 12,0 * * *' 
  workflow_dispatch:

jobs:
  rastrear_produtos:
    runs-on: ubuntu-latest 

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar as bibliotecas
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o Robô
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

        run: python scraper.py